# Generated by Django 3.1.3 on 2020-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspace', '0002_article_author_category_event_source_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='view_count',
            new_name='read_count',
        ),
    ]
