# Generated by Django 3.1.3 on 2021-01-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspace', '0003_auto_20201230_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='events',
            field=models.ManyToManyField(related_name='articles', to='newspace.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(related_name='events', to='newspace.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to='newspace.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newspace.source'),
        ),
    ]
